# Generated by Django 6.0.5 on 2026-06-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universitysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='umiliki',
            field=models.CharField(blank=True, choices=[('Private', 'Private'), ('Goverment', 'Goverment')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='type',
            field=models.CharField(blank=True, choices=[('University', 'University'), ('University College', 'University College'), ('Institute', 'Institute'), ('University Compus College', 'University Compus College'), ('Non University', 'Non University')], max_length=40, null=True),
        ),
    ]
